### PR TITLE
Port external query updates

### PR DESCRIPTION
**Pull request by jmschles**
Update variable forwarding code to handle lists in input objects.

### CODE REVIEW

**Comment by binaryseed** [comment]
Can you share a sentence to remind me what kind of bug this was fixing?

**Comment by binaryseed** [comment]
Or was it as simple as "lists in input objects"?

**Comment by jmschles** [comment]
Yeah, specifically, variables in lists inside input objects weren't getting picked up and passed downstream. For example this wouldn't work:

```
query ($type: String) {
  widgetSearch(query: {types: [$type]}) {
    widgets {
      id
    }
  }
}
```

```
{"type": "LARGE"}
```

**Comment by binaryseed** [comment]
Thanks!

**Pull request merged**
